is_debug = false
is_component_build = false
target_cpu = "arm64"
symbol_level = 0
blink_symbol_level = 0
v8_symbol_level = 0
enable_extensions = true
enable_guest_view = true
enable_pdf = true
enable_printing = true
enable_remoting = false
enable_widevine = false
enable_browser_speech_service = true
enable_speech_service = true
enable_on_device_translation = true
use_on_device_model_service = false
enable_media_remoting = false
enable_media_remoting_rpc = false
enable_pdf_ink2 = false
enable_pdf_save_to_drive = false
enable_pdf_translation = false
enable_oop_printing = false
enable_compose = true
enable_lens_desktop = false
enable_glic_internal_resources = false
enable_webui_contextual_tasks_composebox = false
enable_extractors = false
angle_enable_swiftshader = false
dawn_use_swiftshader = false
enable_swiftshader = false
enable_swiftshader_vulkan = false
use_remoteexec = false
use_siso = true
